"""Demo photos (start/end position) for a subset of EXERCISE_TEMPLATES.

Sourced from free-exercise-db (github.com/yuhonas/free-exercise-db, MIT
licensed) and keyed by the exact template name from seed_data.EXERCISE_TEMPLATES,
since a forked exercise keeps that name verbatim (db.fork_exercise_from_template).
Templates with no reasonable match in that dataset are simply absent here.
"""

import os

MEDIA_DIR = os.path.join(os.path.dirname(__file__), "media", "exercises")

EXERCISE_IMAGE_SLUGS = {
    'Боковая планка': 'side_bridge',
    'Болгарские выпады': 'split_squat_with_dumbbells',
    'Велосипедные скручивания': 'air_bike',
    'Выпады с гантелями': 'dumbbell_lunges',
    'Выпады со штангой': 'barbell_lunge',
    'Гак-присед': 'hack_squat',
    'Гиперэкстензия': 'hyperextensions_back_extensions',
    'Жим Арнольда': 'arnold_dumbbell_press',
    'Жим в тренажёре': 'machine_bench_press',
    'Жим в тренажёре Хаммер': 'leverage_chest_press',
    'Жим в тренажёре на плечи': 'machine_shoulder_military_press',
    'Жим гантелей лёжа': 'dumbbell_bench_press',
    'Жим гантелей на наклонной скамье': 'incline_dumbbell_press',
    'Жим гантелей на наклонной скамье вниз головой': 'decline_dumbbell_bench_press',
    'Жим гантелей сидя': 'seated_dumbbell_press',
    'Жим гантелей стоя': 'standing_dumbbell_press',
    'Жим ногами': 'leg_press',
    'Жим штанги лёжа': 'barbell_bench_press_medium_grip',
    'Жим штанги на наклонной скамье': 'barbell_incline_bench_press_medium_grip',
    'Жим штанги на наклонной скамье вниз головой': 'decline_barbell_bench_press',
    'Жим штанги стоя': 'standing_military_press',
    'Жим штанги узким хватом лёжа': 'close_grip_barbell_bench_press',
    'Зашагивания на платформу': 'dumbbell_step_ups',
    'Колесо для пресса': 'ab_roller',
    'Концентрированный подъём на бицепс': 'concentration_curls',
    'Махи в кроссовере': 'standing_low_pulley_deltoid_raise',
    'Обратные разведения в тренажёре': 'reverse_machine_flyes',
    'Отведение ноги в кроссовере': 'glute_kickback',
    'Отжимания на брусьях': 'dips_chest_version',
    'Отжимания от пола': 'pushups',
    'Отжимания узким хватом': 'push_ups_close_triceps_position',
    'Планка': 'plank',
    'Подтягивания': 'pullups',
    'Подтягивания обратным хватом': 'chin_up',
    'Подъём EZ-штанги на бицепс': 'ez_bar_curl',
    'Подъём гантелей на бицепс': 'dumbbell_bicep_curl',
    'Подъём гантелей на бицепс молотом': 'hammer_curls',
    'Подъём гантелей на бицепс на наклонной скамье': 'incline_dumbbell_curl',
    'Подъём гантелей перед собой': 'front_dumbbell_raise',
    'Подъём коленей в висе': 'knee_hip_raise_on_parallel_bars',
    'Подъём на бицепс в тренажёре': 'machine_bicep_curl',
    'Подъём на бицепс на скамье Скотта': 'preacher_curl',
    'Подъём на носки сидя': 'seated_calf_raise',
    'Подъём на носки стоя': 'standing_calf_raises',
    'Подъём ног в висе': 'hanging_leg_raise',
    'Подъём ног лёжа': 'flat_bench_lying_leg_raise',
    'Подъём штанги на бицепс': 'barbell_curl',
    'Подъём штанги перед собой': 'standing_front_barbell_raise_over_head',
    'Присед в Смите': 'smith_machine_squat',
    'Присед со штангой': 'barbell_squat',
    'Пулловер': 'straight_arm_dumbbell_pullover',
    'Разведение гантелей в наклоне': 'reverse_flyes',
    'Разведение гантелей в стороны': 'side_lateral_raise',
    'Разведение гантелей лёжа': 'dumbbell_flyes',
    'Разведение гантелей на наклонной скамье': 'incline_dumbbell_flyes',
    'Разведение ног в тренажёре': 'thigh_abductor',
    'Разгибание гантели за головой': 'standing_dumbbell_triceps_extension',
    'Разгибание запястий со штангой': 'seated_palms_down_barbell_wrist_curl',
    'Разгибание на трицепс в кроссовере одной рукой': 'cable_one_arm_tricep_extension',
    'Разгибание на трицепс из-за головы на блоке': 'cable_rope_overhead_triceps_extension',
    'Разгибание на трицепс на блоке': 'triceps_pushdown',
    'Разгибание на трицепс на блоке обратным хватом': 'reverse_grip_triceps_pushdown',
    'Разгибание на трицепс на блоке с канатом': 'triceps_pushdown_rope_attachment',
    'Разгибание ног в тренажёре': 'leg_extensions',
    'Разгибание руки с гантелью в наклоне': 'tricep_dumbbell_kickback',
    'Румынская тяга': 'romanian_deadlift',
    'Русские повороты': 'russian_twist',
    'Сведение ног в тренажёре': 'thigh_adductor',
    'Сведение рук в кроссовере': 'cable_crossover',
    'Сведение рук в тренажёре «бабочка»': 'butterfly',
    'Сгибание запястий со штангой': 'seated_palm_up_barbell_wrist_curl',
    'Сгибание ног в тренажёре': 'lying_leg_curls',
    'Сгибание ног сидя в тренажёре': 'seated_leg_curl',
    'Сгибание рук в блоке': 'standing_biceps_cable_curl',
    'Сгибание рук на бицепс обратным хватом': 'reverse_barbell_curl',
    'Сгибание рук на бицепс с канатом в кроссовере': 'cable_hammer_curls_rope_attachment',
    'Скручивания': 'crunches',
    'Скручивания в блоке': 'cable_crunch',
    'Скручивания на наклонной скамье': 'decline_crunch',
    'Становая тяга': 'barbell_deadlift',
    'Становая тяга сумо': 'sumo_deadlift',
    'Тяга Т-грифа': 't_bar_row_with_handle',
    'Тяга в тренажёре Хаммер': 'leverage_high_row',
    'Тяга верхнего блока': 'wide_grip_lat_pulldown',
    'Тяга верхнего блока обратным хватом': 'underhand_cable_pulldowns',
    'Тяга верхнего блока узким хватом': 'close_grip_front_lat_pulldown',
    'Тяга гантелей лёжа на наклонной скамье': 'dumbbell_incline_row',
    'Тяга гантели в наклоне': 'one_arm_dumbbell_row',
    'Тяга на прямых ногах': 'stiff_legged_barbell_deadlift',
    'Тяга нижнего блока': 'seated_cable_rows',
    'Тяга штанги в наклоне': 'bent_over_barbell_row',
    'Тяга штанги в наклоне обратным хватом': 'reverse_grip_bent_over_rows',
    'Тяга штанги к подбородку': 'upright_barbell_row',
    'Французский жим': 'ez_bar_skullcrusher',
    'Французский жим с гантелями': 'lying_dumbbell_tricep_extension',
    'Фронтальный присед': 'front_barbell_squat',
    'Шраги с гантелями': 'dumbbell_shrug',
    'Шраги со штангой': 'barbell_shrug',
    'Ягодичный мостик': 'butt_lift_bridge',
    'Ягодичный мостик со штангой': 'barbell_glute_bridge',
}


def get_images(exercise_name: str) -> list[str]:
    """Absolute paths to the [start, end] position photos, or [] if none exist."""
    slug = EXERCISE_IMAGE_SLUGS.get(exercise_name)
    if slug is None:
        return []
    paths = [os.path.join(MEDIA_DIR, f"{slug}_1.jpg"), os.path.join(MEDIA_DIR, f"{slug}_2.jpg")]
    return paths if all(os.path.exists(p) for p in paths) else []
