"""Демонстрация упражнения одной картинкой: четыре фазы движения нашим тренером.

Запускается руками и локально — в бот этот файл не попадает, в бот попадает
только результат: `media/exercises/<slug>_demo.jpg`. Бот сам ничего не
генерирует, он отдаёт готовый файл (exercise_media.get_collage).

Зачем: в карточке упражнения сейчас пара фотографий из открытой базы, и на них
случайный человек — единственное место в продукте, где вместо нашего тренера
кто-то другой (TONE_OF_VOICE.md, «Стиль картинок»: персонаж один на весь
продукт). Плюс двумя кадрами движение видно плохо: есть начало и конец, а как
между ними — догадайся сам.

Стадии две:

    sheet    эталон тренера + фото упражнения → одна картинка, сетка 2×2
    install  принятая картинка → media/exercises/<slug>_demo.jpg

Почему все четыре фазы одним рендером, а не четырьмя запросами: внутри ОДНОЙ
картинки модель не может нарисовать двух разных мужиков, два разных зала и два
разных света. Проверено дорогой ценой — когда кадры рисовались по отдельности,
между ними менялись очки (золотые авиаторы на чёрные), кроссовки (белые на
чёрные), стойка и крупность. В сетке это сходится само.

Позу модель берёт с фотографии, но фотографии мало: первый прогон дал присед
в нижней точке там, где на фото мужик стоит в полный рост. Картинку модель
смотрит, а рисует по тексту, поэтому позу с фото сперва читает vision-модель,
и в рисование движение едет ещё и фразой.

Примеры:

    python scripts/gen_exercise_demos.py status
    python scripts/gen_exercise_demos.py sheet   --exercise "Присед со штангой"
    python scripts/gen_exercise_demos.py install --exercise "Присед со штангой"

    python scripts/gen_exercise_demos.py pilot --dry-run   # пять упражнений, без трат
    python scripts/gen_exercise_demos.py pilot
    python scripts/gen_exercise_demos.py sheet --all       # все сто

Нужно из окружения:

    OPENAI_API_KEY   тот же ключ, которым бот расшифровывает голосовые

Видеомодель отсюда убрана намеренно. Пробовали Vidu Q1 через Novita: она вшивает
в каждый кадр «Generated by AI» поверх ног, а до нижней точки за пять секунд
так и не доходит. Обрезать вотермарк нельзя — в приседе ноги это половина
смысла. Коллаж показывает движение честнее и не зависит от чужого тарифа.
"""

import argparse
import base64
import json
import os
import pathlib
import shutil
import sys
import urllib.error
import urllib.request

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

import exercise_media  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
MEDIA_DIR = pathlib.Path(exercise_media.MEDIA_DIR)
# Черновики лежат отдельно от готовых ассетов и не коммитятся: на принятую
# картинку приходится несколько отбракованных дублей, и им в репозитории нечего
# делать. В media/exercises переезжает только то, что прошло стадию install.
WORK_DIR = MEDIA_DIR / "_demo_work"

# Пилот: пять разных механик — ноги, жим, тяга, изоляция, статика. Если
# генератор врёт, врать он будет по-разному, и на однотипной пятёрке это
# не вылезет.
PILOT = [
    "Присед со штангой",
    "Жим штанги лёжа",
    "Тяга верхнего блока",
    "Подъём штанги на бицепс",
    "Планка",
]

# Персонаж — дословно по TONE_OF_VOICE.md, раздел «Стиль картинок». Меняется
# только вместе с ним: разъедутся — в карточках заведётся второй тренер.
# Зал описан отдельной строкой и в промпт НЕ идёт: зал приезжает с фотографии
# упражнения, а второе описание зала заставило бы модель выдумывать третий.
CHARACTER_WHO = (
    "huge middle-aged bodybuilder, deep tan, heavy square jaw, short dark-blond "
    "hair combed back, gold aviator sunglasses, thick gold chain, black tank top; "
    "calm confident face, not shouting, not grinning, not winking. "
)
CHARACTER_DRAWING = (
    "Bold black outline, flat fills with soft muscle shading (cel shading), "
    "no photorealism, no 3D render — western comic and arcade-cover look. "
)
CHARACTER_NEVER = (
    "No text, no letters, no numbers, no logos, no watermarks, no other people, "
    "no glossy fitness models, no blood, no grimaces."
)
CHARACTER = CHARACTER_WHO + CHARACTER_DRAWING + CHARACTER_NEVER

COACH_REFERENCE = ROOT / "media" / "push" / "coach_incoming_call.jpg"

SHEET_SIZE = os.getenv("OPENAI_SHEET_SIZE", "1024x1024")
# Качество прямо влияет на цену: low примерно вчетверо дешевле medium, high —
# вчетверо дороже medium. По умолчанию low: подбирать промпт и отбраковывать
# дубли приходится многократно, и платить за это вчетверо незачем. Когда
# картинка устроит — тот же прогон с --force и OPENAI_SHEET_QUALITY=high.
SHEET_QUALITY = os.getenv("OPENAI_SHEET_QUALITY", "low")
SHEET_INSTRUCTION = (
    "Draw ONE image divided into a grid of 2 columns and 2 rows — four equal "
    "panels, edge to edge, with no borders, no gaps, no numbers and no captions. "
    "The four panels are four moments of a single repetition of this exercise, in "
    "order: panel 1 top-left is the very start, panel 2 top-right and panel 3 "
    "bottom-left are the way there, panel 4 bottom-right is the far end. "
    "Between the panels ONLY the body moves: the man, his face, his clothes, his "
    "shoes, the equipment, the gym, the light and the camera position must be "
    "identical in all four, as if a fixed camera shot four frames in a row. "
    "The man is the character from the FIRST image. The equipment, the gym and "
    "the camera framing come from the SECOND image, a photograph of this "
    "exercise; keep its viewpoint, do not restage it. "
    "Move through the FULL range: panel 1 fully at one end, panel 4 fully at the "
    "other, evenly spaced in between — not four nearly identical drawings. "
    "Draw the positions LITERALLY, even when they are not how this exercise is "
    "usually pictured: if the movement starts standing upright, the knees in "
    "panel 1 are locked straight and the hips fully extended. "
    "The movement, from start to end, is: "
)

OPENAI_IMAGE_EDIT_URL = os.getenv(
    "OPENAI_IMAGE_EDIT_URL", "https://api.openai.com/v1/images/edits"
)
OPENAI_CHAT_URL = os.getenv("OPENAI_CHAT_URL", "https://api.openai.com/v1/chat/completions")
OPENAI_IMAGE_MODEL = os.getenv("OPENAI_IMAGE_MODEL", "gpt-image-1")
OPENAI_VISION_MODEL = os.getenv("OPENAI_VISION_MODEL", "gpt-4o-mini")
USER_AGENT = "training-log-bot-exercise-demos/1.0"

# Прочитанные движения лежат файлом и коммитятся: читаются один раз, а
# перерисовывать картинку приходится многократно, и платить за одно и то же
# чтение каждый раз незачем.
POSES_PATH = pathlib.Path(__file__).resolve().parent / "exercise_poses.json"
POSE_QUESTION = (
    "These two photos are the start and the end of one repetition of a gym "
    "exercise. In two English sentences, for an artist who will draw the whole "
    "movement: describe the body position in the first photo, then how it changes "
    "by the second — which joints bend, how far, where the weight travels. "
    "Do not describe the gym, the clothes or the person's appearance."
)


class GenError(RuntimeError):
    """Провайдер ответил не тем, чего мы ждали. Текст ответа внутри."""


def _api_key() -> str:
    key = os.getenv("OPENAI_API_KEY", "")
    if not key:
        sys.exit(
            "Нет OPENAI_API_KEY в окружении. Это тот же ключ, которым бот "
            "расшифровывает голосовые. Прогон без трат: добавь --dry-run."
        )
    return key


def _b64(path: pathlib.Path) -> str:
    return base64.b64encode(path.read_bytes()).decode()


def _post(url: str, data: bytes, content_type: str) -> dict:
    req = urllib.request.Request(
        url,
        data=data,
        headers={
            "Authorization": f"Bearer {_api_key()}",
            "Content-Type": content_type,
            "User-Agent": USER_AGENT,
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=600) as resp:
            return json.loads(resp.read())
    except urllib.error.HTTPError as e:
        # Тело ответа дословно: при расхождении с доками там лежит имя поля,
        # которое не сошлось, и это разница между «правка на минуту» и
        # «непонятная 400».
        raise GenError(f"HTTP {e.code} от {url}\n{e.read().decode(errors='replace')}") from e


def _multipart(fields: dict[str, str], files: list[tuple[str, pathlib.Path]]) -> tuple[bytes, str]:
    """Тело multipart/form-data. Граница фиксированная: случайность тут ничего
    не даёт, а воспроизводимый запрос удобнее отлаживать."""
    boundary = "----trainingLogBotExerciseDemos"
    body = bytearray()
    for name, value in fields.items():
        body += f'--{boundary}\r\nContent-Disposition: form-data; name="{name}"\r\n\r\n'.encode()
        body += f"{value}\r\n".encode()
    for name, path in files:
        body += (
            f'--{boundary}\r\nContent-Disposition: form-data; name="{name}"; '
            f'filename="{path.name}"\r\nContent-Type: image/jpeg\r\n\r\n'
        ).encode()
        body += path.read_bytes() + b"\r\n"
    body += f"--{boundary}--\r\n".encode()
    return bytes(body), boundary


# --- Чтение движения с фотографий -------------------------------------------


def _read_movement(first: pathlib.Path, second: pathlib.Path) -> str:
    """Что за движение на паре фото — двумя фразами, глазами vision-модели.

    Читается по самим фотографиям, а не сочиняется по названию упражнения: фото
    и есть источник правды про технику, а словами оно становится только чтобы
    рисующая модель его наконец услышала.
    """
    payload = {
        "model": OPENAI_VISION_MODEL,
        "messages": [
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": POSE_QUESTION},
                    *[
                        {
                            "type": "image_url",
                            "image_url": {"url": f"data:image/jpeg;base64,{_b64(photo)}"},
                        }
                        for photo in (first, second)
                    ],
                ],
            }
        ],
    }
    answer = _post(OPENAI_CHAT_URL, json.dumps(payload).encode(), "application/json")
    return answer["choices"][0]["message"]["content"].strip()


def _load_poses() -> dict[str, str]:
    return json.loads(POSES_PATH.read_text()) if POSES_PATH.exists() else {}


def _movement_for(slug: str, dry_run: bool, force: bool) -> str:
    poses = _load_poses()
    if slug in poses and not force:
        return poses[slug]
    if dry_run:
        return f"<движение, прочитанное с {slug}_1.jpg и {slug}_2.jpg>"
    print("    читаю движение с пары фото")
    poses[slug] = _read_movement(MEDIA_DIR / f"{slug}_1.jpg", MEDIA_DIR / f"{slug}_2.jpg")
    POSES_PATH.write_text(json.dumps(poses, indent=2, ensure_ascii=False, sort_keys=True))
    return poses[slug]


# --- Стадии -----------------------------------------------------------------


def _slug(exercise: str) -> str:
    slug = exercise_media.EXERCISE_IMAGE_SLUGS.get(exercise)
    if slug is None:
        sys.exit(
            f"Упражнения {exercise!r} нет в EXERCISE_IMAGE_SLUGS. "
            "Список того, что есть: status."
        )
    return slug


def _work(slug: str, create: bool = True) -> pathlib.Path:
    """Каталог черновиков упражнения. create=False для сухого прогона: он не
    должен оставлять после себя пустых папок, которые status потом покажет
    как «в работе»."""
    path = WORK_DIR / slug
    if create:
        path.mkdir(parents=True, exist_ok=True)
    return path


def cmd_sheet(exercise: str, dry_run: bool, force: bool) -> None:
    slug = _slug(exercise)
    work = _work(slug, create=not dry_run)
    dest = work / "sheet.jpg"
    if dest.exists() and not force:
        print("  sheet.jpg уже есть, пропускаю (--force чтобы перерисовать)")
        return
    movement = _movement_for(slug, dry_run, force=False)
    prompt = f"{SHEET_INSTRUCTION}{movement} {CHARACTER}"
    # Фото конечного положения, а не стартового: у него в кадре видна вся
    # амплитуда — на стартовом мужик часто просто стоит, и по нему одному не
    # понять, куда он поедет.
    pose_photo = MEDIA_DIR / f"{slug}_2.jpg"
    print(f"  {slug}: четыре фазы одной картинкой")
    if dry_run:
        print(
            f"    POST {OPENAI_IMAGE_EDIT_URL}, model={OPENAI_IMAGE_MODEL}, "
            f"size={SHEET_SIZE}, quality={SHEET_QUALITY}"
        )
        print(f"    image=[{COACH_REFERENCE.name} (тренер), {pose_photo.name} (упражнение)]")
        print(f"    движение: {movement}")
        return
    if not COACH_REFERENCE.exists():
        sys.exit(f"Нет эталона тренера: {COACH_REFERENCE}")
    body, boundary = _multipart(
        {
            "model": OPENAI_IMAGE_MODEL,
            "prompt": prompt,
            "size": SHEET_SIZE,
            "quality": SHEET_QUALITY,
            "n": "1",
        },
        # Порядок значим: промпт ссылается на «первую» и «вторую» картинку.
        [("image[]", COACH_REFERENCE), ("image[]", pose_photo)],
    )
    payload = _post(
        OPENAI_IMAGE_EDIT_URL, body, f"multipart/form-data; boundary={boundary}"
    )
    try:
        image_b64 = payload["data"][0]["b64_json"]
    except (KeyError, IndexError) as e:
        raise GenError(f"Ответ без картинки: {json.dumps(payload)[:400]}") from e
    dest.write_bytes(base64.b64decode(image_b64))
    print(f"    готово: {dest}")
    print("    Смотри глазами: четыре РАЗНЫХ положения, тренер один и тот же.")
    print("    Не то — перерисуй: sheet --force. То — ставь: install.")


def cmd_install(exercise: str, dry_run: bool, force: bool) -> None:
    slug = _slug(exercise)
    sheet = _work(slug, create=not dry_run) / "sheet.jpg"
    dest = MEDIA_DIR / f"{slug}_demo.jpg"
    print(f"  {sheet} → {dest}")
    if dry_run:
        return
    if not sheet.exists():
        raise GenError(f"Сначала картинка: sheet --exercise {exercise!r}")
    if dest.exists() and not force:
        print(f"  {dest.name} уже стоит, пропускаю (--force чтобы заменить)")
        return
    shutil.copyfile(sheet, dest)
    print("    готово. Картинка подхватится сама, пересобирать ничего не надо.")


def cmd_status(*_args, **_kwargs) -> None:
    ready, drafts = [], []
    for exercise, slug in sorted(exercise_media.EXERCISE_IMAGE_SLUGS.items()):
        if (MEDIA_DIR / f"{slug}_demo.jpg").exists():
            ready.append(exercise)
        elif (WORK_DIR / slug).exists():
            drafts.append(exercise)
    total = len(exercise_media.EXERCISE_IMAGE_SLUGS)
    print(f"Готовых демонстраций: {len(ready)} из {total}")
    for exercise in ready:
        print(f"  ✅ {exercise}")
    if drafts:
        print(f"В работе (есть черновик, не поставлен): {len(drafts)}")
        for exercise in drafts:
            print(f"  🚧 {exercise}")
    print(f"Остальные {total - len(ready)} показывают прежнюю пару фото.")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Демонстрации упражнений: шесть фаз движения одной картинкой.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("stage", choices=["sheet", "install", "status", "pilot"])
    parser.add_argument("--exercise", help="название упражнения ровно как в шаблонах")
    parser.add_argument("--all", action="store_true", help="все упражнения с фото")
    parser.add_argument(
        "--dry-run", action="store_true", help="показать запросы, ничего не тратить"
    )
    parser.add_argument("--force", action="store_true", help="перезаписать готовое")
    args = parser.parse_args()

    if args.stage == "status":
        cmd_status()
        return

    stages = {"sheet": cmd_sheet, "install": cmd_install}
    if args.stage == "pilot":
        targets, chain = PILOT, list(stages.values())
    elif args.all:
        targets, chain = sorted(exercise_media.EXERCISE_IMAGE_SLUGS), [stages[args.stage]]
    elif args.exercise:
        targets, chain = [args.exercise], [stages[args.stage]]
    else:
        parser.error("нужен --exercise, --all или стадия pilot")

    failed = []
    for exercise in targets:
        print(f"\n=== {exercise}")
        for stage in chain:
            try:
                stage(exercise, args.dry_run, args.force)
            except GenError as e:
                # Одно упавшее упражнение не должно ронять весь прогон: на
                # длинном --all это значит «потерять всё из-за одной задачи».
                print(f"  ❌ {e}")
                failed.append(exercise)
                break
    if failed:
        print(f"\nНе получилось: {', '.join(failed)}")
        sys.exit(1)


if __name__ == "__main__":
    main()
